### PR TITLE
wip

### PR DESCRIPTION
**Pull request by mkasenberg**
bot testing

### CODE REVIEW

**Comment by mkasenberg** [comment]
#AutoPTS run host

**Comment by mkasenberg** [comment]
#AutoPTS run host

**Comment by mkasenberg** [comment]
#AutoPTS run host

**Comment by mkasenberg** [comment]
#AutoPTS run host

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No regressions found.
No progresses found.

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Found regressions:
GAP     GAP/CONN/PRDA/BV-02-C           INCONC - REGRESSION 
No progresses found.

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Found regressions:
GAP     GAP/CONN/PRDA/BV-02-C           INCONC - REGRESSION 
No progresses found.

**Comment by mkasenberg** [comment]
#AutoPTS run GAP/CONN/PRDA/BV-02-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Found regressions:
GAP     GAP/CONN/PRDA/BV-02-C           INCONC - REGRESSION 
No progresses found.

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr SM

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr SM

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr SM

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr SM

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr SM

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr GAP/ADV/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 11:22:18.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 11:26:30.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 12:07:28.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 12:49:18.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 14:53:55.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 15:05:13.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 15:30:18.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 15:44:43.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1543642839 after 15:52:41.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr GAP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1545286729 after 09:15:45.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1545286729 after 09:21:58.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1545286729 after 09:28:00.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>zephyr=491628ae0614377ae64788ca3641c7698c63147a, autopts=35f75f20e925d1c03ddfe2bcbd2c38cdb189dbc5-dirty<br>GAP     GAP/BROB/BCST/BV-01-C           PASS<br>GAP     GAP/BROB/BCST/BV-02-C           PASS<br>GAP     GAP/BROB/OBSV/BV-01-C           PASS<br>GAP     GAP/BROB/OBSV/BV-02-C           PASS<br>GAP     GAP/BROB/OBSV/BV-05-C           PASS</details>

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr GAP/SEC/SEM/BV-6

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1545311642 after 09:38:18.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/SEC/SEM/BV-62-C             INCONC - ERRATA TSE18349<br>GAP     GAP/SEC/SEM/BV-63-C             INCONC - ERRATA TSE18349<br>GAP     GAP/SEC/SEM/BV-64-C             INCONC - ERRATA TSE18349<br>GAP     GAP/SEC/SEM/BV-65-C             INCONC - ERRATA TSE18349</details>
<details><summary>Successful tests</summary>GAP     GAP/SEC/SEM/BV-60-C             PASS</details>

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr GAP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1693345815 after 15:15:58.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/mkasenberg/zephyr/pull/1#issuecomment-1693345815 after 15:20:32.

**Pull request merged**
